#!/usr/bin/env node

import { generateScramble, generateScrambleSync, verifyScrambleSync } from '.';
import yargs = require('yargs');
import { hideBin } from 'yargs/helpers';

yargs(hideBin(process.argv))
    .scriptName('scrambled')
    .command('generate [-s/--size] [-c/--count]', 'Generates a scramble.', (yargs) => {
        yargs
            .option('size', {
                alias: 's',
                default: 3
            })
            .option('count', {
                alias: 'c',
                default: 30
            });
    }, (argv) => {
        let scramble;
        if (typeof argv.count == 'number' && typeof argv.size == 'number')
            scramble = generateScrambleSync(argv.count, argv.size);

        console.log('Authentication:', scramble.token);
        console.log(scramble.scramble);
    })
    .command('verify [-t/--token] [-s/--scramble] [-S/--size]', 'Verifies that a scramble was generated with Scrambled.', (yargs) => {
        yargs
            .option('token', {
                alias: 't',
                required: true
            })
            .option('scramble', {
                alias: 's',
                required: true
            })
            .option('size', {
                alias: 'S',
                default: 3
            })
    }, (argv) => {
        if (typeof argv.token == 'string' && typeof argv.scramble == 'string' && typeof argv.size == 'number') {
            let res = verifyScrambleSync(argv.token, argv.scramble,  argv.scramble.split(' ').length, argv.size);

            if (res)
                return console.log('This scramble was generated by Scrambled.');
            
            console.log('This scramble wasn\'t generated with Scrambled.');
        }
    })
    .argv